#!/bin/bash

source ../cascade-make/lib/cascade-lib.bash $*

# 1. With introspection: for d in PKG-CONFIG M4 AUTOCONF AUTOMAKE LIBTOOL ZLIB GLIB PIXMAN LIBPNG JPEG TIFF FREETYPE FONTCONFIG CAIRO FLEX BISON LIBFFI GOBJECT-INTROSPECTION GDK-PIXBUF PANGO ATK XORG-MACROS XORG-PROTO XCB-PROTO LIBXAU PTHREAD-STUBS LIBXCB LIBXTRANS PERL LIBX11 LIBXRENDER GTK+ WXWIDGETS ESPEAK-NG ; do
# 2. Compile x11 before Cairo: for d in PKG-CONFIG M4 AUTOCONF AUTOMAKE LIBTOOL ZLIB GLIB PIXMAN LIBPNG JPEG TIFF FREETYPE FONTCONFIG CAIRO GDK-PIXBUF PANGO ATK XORG-MACROS XORG-PROTO XCB-PROTO LIBXAU PTHREAD-STUBS LIBXCB LIBXTRANS PERL LIBX11 LIBXRENDER GTK+ WXWIDGETS PORTAUDIO ; do
for d in MAKE PKG-CONFIG M4 AUTOCONF AUTOMAKE LIBTOOL ZLIB LIBFFI GLIB PIXMAN LIBPNG JPEG TIFF FREETYPE FONTCONFIG XORG-MACROS XORG-PROTO XCB-PROTO LIBXAU PTHREAD-STUBS LIBXCB LIBXTRANS PERL LIBX11 LIBXRENDER CAIRO GDK-PIXBUF PANGO ATK GTK+ WXWIDGETS PORTAUDIO ESPEAKEDIT ; do
    echo "    Running CASCADE-MAKE-SCRIPTS/$d.sh"

    ./CASCADE-MAKE-SCRIPTS/$d.sh $*

    if [ $? != 0 ] ; then
	echo "Error encountered running CASCADE-MAKE/$d.sh"
	exit 1
    fi
done
