
export MYSQL_COMPLETE_HOME=`pwd`
echo "Set MYSQL_COMPLETE_HOME = $MYSQL_COMPLETE_HOME"

export MYSQL_COMPLETE_INSTALLED=$MYSQL_COMPLETE_HOME/linux
echo "Set MYSQL_COMPLETE_INSTALLED = $MYSQL_COMPLETE_INSTALLED"


export PATH=$MYSQL_COMPLETE_INSTALLED/bin:$PATH

echo "PATH updated to include: $MYSQL_COMPLETE_INSTALLED/bin"
