
export MYSQL_COMPLETE_HOME=`pwd`
echo "Set MYSQL_COMPLETE_HOME = $MYSQL_COMPLETE_HOME"

export MYSQL_COMPLETE_INSTALLED=$MYSQL_COMPLETE_HOME/linux
echo "Set MYSQL_COMPLETE_INSTALLED = $MYSQL_COMPLETE_INSTALLED"


export PATH=$MYSQL_COMPLETE_INSTALLED/bin:$MYSQL_COMPLETE_INSTALLED/mysql/bin:$PATH

echo "PATH updated to include: $MYSQL_COMPLETE_INSTALLED/{bin,mysql/bin}"

if [ "x$LD_LIBRARY_PATH" = "x" ] ;then
    export LD_LIBRARY_PATH=$MYSQL_COMPLETE_INSTALLED/lib
    echo "set LD_LIBRARY_PATH to: $MYSQL_COMPLETE_INSTALLED/lib"
else
    export LD_LIBRARY_PATH=$MYSQL_COMPLETE_INSTALLED/lib:$LD_LIBRARY_PATH
    echo "prepended to LD_LIBRARY_PATH: $MYSQL_COMPLETE_INSTALLED/lib"
	
fi

